# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loadsystem.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(574, 601)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMaximumSize(QtCore.QSize(16666, 16666))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setEnabled(False)
        self.label.setGeometry(QtCore.QRect(0, 0, 581, 321))
        self.label.setStyleSheet("QLabel{border-image:url(:/login/wallpaper/e327a46f1c5ca5f2297428bf83a3ad2218c41ae1.jpg)}\n"
"\n"
"\n"
"\n"
"")
        self.label.setText("")
        self.label.setObjectName("label")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 319, 571, 281))
        self.widget.setObjectName("widget")
        self.login_button = QtWidgets.QPushButton(self.widget)
        self.login_button.setEnabled(True)
        self.login_button.setGeometry(QtCore.QRect(140, 170, 228, 45))
        self.login_button.setMinimumSize(QtCore.QSize(0, 45))
        self.login_button.setMaximumSize(QtCore.QSize(16777215, 45))
        self.login_button.setStyleSheet("QPushButton {\n"
"    background-color: rgb(33,174,250);\n"
"    border-radius: 5px;\n"
"    color: white;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(72,203,250);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(85,85,255);\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color: rgb(148, 146, 149);\n"
"}")
        self.login_button.setObjectName("login_button")
        self.pwd_label = QtWidgets.QLineEdit(self.widget)
        self.pwd_label.setGeometry(QtCore.QRect(140, 90, 228, 45))
        self.pwd_label.setMinimumSize(QtCore.QSize(0, 45))
        self.pwd_label.setMaximumSize(QtCore.QSize(16777215, 45))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(-1)
        self.pwd_label.setFont(font)
        self.pwd_label.setStyleSheet("QLineEdit {\n"
"    font-size: 20px;\n"
"    border: none;\n"
"    border-bottom: 1px solid gray;\n"
"    background-color: transparent;\n"
"}\n"
"QLineEdit: hover{\n"
"    border-bottom: 1px solid black;\n"
"}\n"
"QLineEdit: focus \n"
"{\n"
"     border-bottom: 1px solid rgb(18,183,245);\n"
"}")
        self.pwd_label.setText("")
        self.pwd_label.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pwd_label.setObjectName("pwd_label")
        self.account_label = QtWidgets.QLineEdit(self.widget)
        self.account_label.setGeometry(QtCore.QRect(140, 20, 228, 45))
        self.account_label.setMinimumSize(QtCore.QSize(0, 45))
        self.account_label.setMaximumSize(QtCore.QSize(16777215, 45))
        self.account_label.setStyleSheet("QLineEdit {\n"
"    font-size: 20px;\n"
"    border: none;\n"
"    border-bottom: 1px solid gray;\n"
"    background-color: transparent;\n"
"}\n"
"QLineEdit: hover{\n"
"    border-bottom: 1px solid black;\n"
"}\n"
"QLineEdit: focus \n"
"{\n"
"     border-bottom: 1px solid rgb(18,183,245);\n"
"}")
        self.account_label.setText("")
        self.account_label.setObjectName("account_label")
        self.register2_label = QtWidgets.QPushButton(self.widget)
        self.register2_label.setGeometry(QtCore.QRect(10, 212, 91, 31))
        self.register2_label.setFlat(True)
        self.register2_label.setObjectName("register2_label")
        self.zhanghao_label = QtWidgets.QLabel(self.widget)
        self.zhanghao_label.setEnabled(False)
        self.zhanghao_label.setGeometry(QtCore.QRect(60, 31, 71, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(18)
        self.zhanghao_label.setFont(font)
        self.zhanghao_label.setObjectName("zhanghao_label")
        self.mima_label = QtWidgets.QLabel(self.widget)
        self.mima_label.setEnabled(False)
        self.mima_label.setGeometry(QtCore.QRect(60, 101, 71, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(18)
        self.mima_label.setFont(font)
        self.mima_label.setObjectName("mima_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Ph登录平台"))
        self.login_button.setText(_translate("MainWindow", "登陆"))
        self.register2_label.setText(_translate("MainWindow", "注册"))
        self.zhanghao_label.setText(_translate("MainWindow", "账号"))
        self.mima_label.setText(_translate("MainWindow", "密码"))
import resource.source_rc
